version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9093:9093"
    volumes:
      - D:\kafka_data:/bitnami/kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@host.docker.internal:9093
      # Client credentials
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=admin
      - KAFKA_CLIENT_LISTENER_NAME=LISTENER_EXTERNAL
      # Controller credentials
      - KAFKA_CONTROLLER_USER=admin
      - KAFKA_CONTROLLER_PASSWORD=admin
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      # Inter-broker credentials
      - KAFKA_INTER_BROKER_USER=admin
      - KAFKA_INTER_BROKER_PASSWORD=admin
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      # Listeners
        # Specify Container Local port
      - KAFKA_CFG_LISTENERS=LISTENER_DOCKER://:29092,LISTENER_EXTERNAL://:9092,CONTROLLER://:9093
        # Specify Host:Port for the Client to connect
        # Using kafka UI or other services that run in Docker: connect to host.docker.internal:29092
        # Services running on host: connect to localhost:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_DOCKER://host.docker.internal:29092,LISTENER_EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,LISTENER_DOCKER:SASL_PLAINTEXT,LISTENER_EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER